# Generated by Django 4.0.5 on 2022-06-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_score_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='teesPlayed',
        ),
    ]
