# Generated by Django 4.0.5 on 2022-07-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holescore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=32)),
                ('hole1', models.IntegerField()),
                ('hole2', models.IntegerField()),
                ('hole3', models.IntegerField()),
                ('hole4', models.IntegerField()),
                ('hole5', models.IntegerField()),
                ('hole6', models.IntegerField()),
                ('hole7', models.IntegerField()),
                ('hole8', models.IntegerField()),
                ('hole9', models.IntegerField()),
                ('hole10', models.IntegerField()),
                ('hole11', models.IntegerField()),
                ('hole12', models.IntegerField()),
                ('hole13', models.IntegerField()),
                ('hole14', models.IntegerField()),
                ('hole15', models.IntegerField()),
                ('hole16', models.IntegerField()),
                ('hole17', models.IntegerField()),
                ('hole18', models.IntegerField()),
            ],
        ),
    ]
