# Generated by Django 4.0.5 on 2022-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('hole1Score', models.IntegerField()),
                ('hole2Score', models.IntegerField()),
                ('hole3Score', models.IntegerField()),
                ('hole4Score', models.IntegerField()),
                ('hole5Score', models.IntegerField()),
                ('hole6Score', models.IntegerField()),
                ('hole7Score', models.IntegerField()),
                ('hole8Score', models.IntegerField()),
                ('hole9Score', models.IntegerField()),
                ('hole10Score', models.IntegerField()),
                ('hole11Score', models.IntegerField()),
                ('hole12Score', models.IntegerField()),
                ('hole13Score', models.IntegerField()),
                ('hole14Score', models.IntegerField()),
                ('hole15Score', models.IntegerField()),
                ('hole16Score', models.IntegerField()),
                ('hole17Score', models.IntegerField()),
                ('hole18Score', models.IntegerField()),
            ],
        ),
    ]
