# Generated by Django 4.0.5 on 2022-06-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('totalYards', models.IntegerField()),
                ('slopeRating', models.IntegerField()),
                ('courseRating', models.IntegerField()),
                ('hole1Yardage', models.IntegerField()),
                ('hole2Par', models.IntegerField()),
                ('hole2Yardage', models.IntegerField()),
                ('hole1Par', models.IntegerField()),
                ('hole3Yardage', models.IntegerField()),
                ('hole3Par', models.IntegerField()),
                ('hole4Yardage', models.IntegerField()),
                ('hole4Par', models.IntegerField()),
                ('hole5Yardage', models.IntegerField()),
                ('hole5Par', models.IntegerField()),
                ('hole6Yardage', models.IntegerField()),
                ('hole6Par', models.IntegerField()),
                ('hole7Yardage', models.IntegerField()),
                ('hole7Par', models.IntegerField()),
                ('hole8Yardage', models.IntegerField()),
                ('hole8Par', models.IntegerField()),
                ('hole9Yardage', models.IntegerField()),
                ('hole9Par', models.IntegerField()),
                ('hole10Yardage', models.IntegerField()),
                ('hole10Par', models.IntegerField()),
                ('hole11Yardage', models.IntegerField()),
                ('hole11Par', models.IntegerField()),
                ('hole12Yardage', models.IntegerField()),
                ('hole12Par', models.IntegerField()),
                ('hole13Yardage', models.IntegerField()),
                ('hole13Par', models.IntegerField()),
                ('hole14Yardage', models.IntegerField()),
                ('hole14Par', models.IntegerField()),
                ('hole15Yardage', models.IntegerField()),
                ('hole15Par', models.IntegerField()),
                ('hole16Yardage', models.IntegerField()),
                ('hole16Par', models.IntegerField()),
                ('hole17Yardage', models.IntegerField()),
                ('hole17Par', models.IntegerField()),
                ('hole18Yardage', models.IntegerField()),
                ('hole18Par', models.IntegerField()),
            ],
        ),
    ]
